import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

const JOBS = [
  // ─── Java / Spring Boot ───────────────────────────────────────────────────
  {
    title: "Senior Java Developer",
    company: "TCS",
    companyDomain: "tcs.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "LINKEDIN",
    applyUrl: "https://www.linkedin.com/jobs/view/senior-java-tcs",
    description: "Build microservices-based applications for banking clients using Java 17, Spring Boot 3, and Kubernetes.",
    requirements: "5+ years Java, Spring Boot, REST APIs, Microservices. Knowledge of JPA/Hibernate, Kafka, Docker.",
    skills: ["Java", "Spring Boot", "Microservices", "Kubernetes", "Kafka", "Docker", "REST API", "Hibernate"],
    salary: { min: 1600000, max: 2800000, currency: "INR" },
    seniority: "Senior",
    postedAt: new Date(Date.now() - 1 * 86400000),
  },
  {
    title: "Java Backend Engineer",
    company: "HCL Technologies",
    companyDomain: "hcltech.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "INDEED",
    applyUrl: "https://www.indeed.com/viewjob?jk=hcl-java-backend",
    description: "Design and develop scalable backend systems for HCL's digital engineering practice. Work with Java, Spring Cloud, and AWS.",
    requirements: "4+ years Java. Spring Cloud, AWS Lambda, DynamoDB experience. Good understanding of design patterns.",
    skills: ["Java", "Spring Cloud", "AWS", "Lambda", "DynamoDB", "REST API", "Maven", "JUnit"],
    salary: { min: 1400000, max: 2400000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 2 * 86400000),
  },
  {
    title: "Java Microservices Architect",
    company: "Cognizant",
    companyDomain: "cognizant.com",
    location: "Bangalore, Karnataka",
    locationType: "ONSITE",
    jobType: "FULL_TIME",
    source: "GREENHOUSE",
    applyUrl: "https://jobs.cognizant.com/java-architect",
    description: "Architect and lead development of cloud-native Java applications. Drive technical decisions and mentor a team of 8 engineers.",
    requirements: "8+ years Java, Spring ecosystem. Experience with event-driven architecture, CQRS, DDD. AWS/Azure certified preferred.",
    skills: ["Java", "Spring Boot", "CQRS", "Event-Driven Architecture", "Azure", "DDD", "Redis", "PostgreSQL"],
    salary: { min: 3000000, max: 4800000, currency: "INR" },
    seniority: "Lead",
    postedAt: new Date(Date.now() - 3 * 86400000),
  },

  // ─── Python ───────────────────────────────────────────────────────────────
  {
    title: "Python Backend Developer",
    company: "Amazon",
    companyDomain: "amazon.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "LINKEDIN",
    applyUrl: "https://www.amazon.jobs/python-backend-bangalore",
    description: "Build and scale distributed services powering Amazon's supply chain platform. Python, Django/FastAPI, AWS native services.",
    requirements: "4+ years Python. Django or FastAPI. Strong in algorithms and data structures. AWS experience required.",
    skills: ["Python", "FastAPI", "Django", "AWS", "PostgreSQL", "Redis", "Celery", "Docker"],
    salary: { min: 3000000, max: 5000000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 1 * 86400000),
  },
  {
    title: "Senior Python Engineer",
    company: "Razorpay",
    companyDomain: "razorpay.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "LEVER",
    applyUrl: "https://jobs.lever.co/razorpay/python-engineer",
    description: "Power India's leading payment gateway with high-performance Python services processing millions of transactions daily.",
    requirements: "4+ years Python, Flask/FastAPI. Strong on concurrency, async programming. SQL and NoSQL databases.",
    skills: ["Python", "Flask", "FastAPI", "Async Python", "MySQL", "MongoDB", "Kafka", "Kubernetes"],
    salary: { min: 2500000, max: 4000000, currency: "INR" },
    seniority: "Senior",
    postedAt: new Date(Date.now() - 2 * 86400000),
  },
  {
    title: "Python Developer – FinTech",
    company: "Zerodha",
    companyDomain: "zerodha.com",
    location: "Bangalore, Karnataka",
    locationType: "ONSITE",
    jobType: "FULL_TIME",
    source: "INDEED",
    applyUrl: "https://zerodha.com/careers/python-developer",
    description: "Join India's largest stock broker to build robust trading systems and back-office automation using Python.",
    requirements: "3+ years Python. Financial domain knowledge a plus. Strong in data processing with Pandas/NumPy.",
    skills: ["Python", "Pandas", "NumPy", "PostgreSQL", "Redis", "Linux", "REST API", "Git"],
    salary: { min: 1800000, max: 3200000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 4 * 86400000),
  },

  // ─── Azure / Cloud ────────────────────────────────────────────────────────
  {
    title: "Azure Cloud Engineer",
    company: "Microsoft",
    companyDomain: "microsoft.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "LINKEDIN",
    applyUrl: "https://careers.microsoft.com/azure-cloud-engineer-bangalore",
    description: "Build and maintain Azure infrastructure for Microsoft's enterprise customers. IaC, monitoring, and cloud security focus.",
    requirements: "4+ years cloud engineering. AZ-104 or AZ-305 certified. Terraform, ARM templates, PowerShell.",
    skills: ["Azure", "Terraform", "ARM Templates", "PowerShell", "Azure DevOps", "AKS", "Monitoring", "Cloud Security"],
    salary: { min: 2800000, max: 4500000, currency: "INR" },
    seniority: "Senior",
    postedAt: new Date(Date.now() - 1 * 86400000),
  },
  {
    title: "Azure Solutions Architect",
    company: "Infosys",
    companyDomain: "infosys.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "INDEED",
    applyUrl: "https://www.indeed.com/viewjob?jk=infosys-azure-architect",
    description: "Design cloud-first solutions on Azure for global banking clients. Lead the cloud migration strategy from on-prem to Azure.",
    requirements: "7+ years IT, 4+ years Azure. AZ-305 required. Experience with Azure Synapse, Data Factory, Logic Apps.",
    skills: ["Azure", "Azure Synapse", "Data Factory", "Logic Apps", "Azure AD", "Cloud Migration", "ARM", "Power BI"],
    salary: { min: 3200000, max: 5500000, currency: "INR" },
    seniority: "Lead",
    postedAt: new Date(Date.now() - 3 * 86400000),
  },
  {
    title: "Cloud DevOps Engineer (AWS/Azure)",
    company: "IBM",
    companyDomain: "ibm.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "GREENHOUSE",
    applyUrl: "https://jobs.greenhouse.io/ibm/cloud-devops",
    description: "Automate cloud infrastructure and CI/CD pipelines for IBM's consulting practice across AWS and Azure.",
    requirements: "3+ years DevOps. Kubernetes, Terraform, Jenkins. AWS or Azure certification preferred.",
    skills: ["AWS", "Azure", "Kubernetes", "Terraform", "Jenkins", "GitLab CI", "Helm", "Prometheus"],
    salary: { min: 1800000, max: 3200000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 2 * 86400000),
  },

  // ─── Full Stack / React ───────────────────────────────────────────────────
  {
    title: "Senior Full Stack Developer (React + Node)",
    company: "Swiggy",
    companyDomain: "swiggy.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "LEVER",
    applyUrl: "https://jobs.lever.co/swiggy/fullstack-engineer",
    description: "Build consumer-facing product features for Swiggy's app used by 50M+ users. React frontend, Node.js microservices.",
    requirements: "4+ years full-stack. React, TypeScript, Node.js, GraphQL. Experience with high-traffic production systems.",
    skills: ["React", "TypeScript", "Node.js", "GraphQL", "PostgreSQL", "Redis", "Docker", "AWS"],
    salary: { min: 2500000, max: 4200000, currency: "INR" },
    seniority: "Senior",
    postedAt: new Date(Date.now() - 1 * 86400000),
  },
  {
    title: "React Frontend Engineer",
    company: "Zomato",
    companyDomain: "zomato.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "LINKEDIN",
    applyUrl: "https://www.linkedin.com/jobs/view/zomato-react-frontend",
    description: "Craft pixel-perfect user interfaces for Zomato's web platform. Own frontend performance, accessibility, and developer experience.",
    requirements: "3+ years React, TypeScript. Next.js experience preferred. Strong CSS, Web Performance fundamentals.",
    skills: ["React", "TypeScript", "Next.js", "CSS", "Redux", "Webpack", "Jest", "Web Performance"],
    salary: { min: 2000000, max: 3500000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 2 * 86400000),
  },
  {
    title: "Full Stack Engineer (MEAN Stack)",
    company: "Wipro",
    companyDomain: "wipro.com",
    location: "Bangalore, Karnataka",
    locationType: "ONSITE",
    jobType: "FULL_TIME",
    source: "INDEED",
    applyUrl: "https://www.indeed.com/viewjob?jk=wipro-mean-stack",
    description: "Develop end-to-end web applications for enterprise clients using MEAN stack. Work in an agile team of 12.",
    requirements: "3+ years MEAN/MERN stack. MongoDB, Express, Angular/React, Node.js. REST API design skills.",
    skills: ["Angular", "Node.js", "MongoDB", "Express.js", "TypeScript", "REST API", "Git", "Agile"],
    salary: { min: 1400000, max: 2400000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 5 * 86400000),
  },

  // ─── .NET ─────────────────────────────────────────────────────────────────
  {
    title: "Senior .NET Developer",
    company: "Capgemini",
    companyDomain: "capgemini.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "ADZUNA",
    applyUrl: "https://www.capgemini.com/careers/dotnet-senior",
    description: "Build enterprise-grade applications with .NET 8, C# for Capgemini's retail and logistics clients. Microservices + Azure.",
    requirements: "5+ years C#/.NET. ASP.NET Core, Entity Framework. Azure knowledge. Strong OOP and design patterns.",
    skills: [".NET", "C#", "ASP.NET Core", "Entity Framework", "Azure", "SQL Server", "Microservices", "Docker"],
    salary: { min: 1800000, max: 3200000, currency: "INR" },
    seniority: "Senior",
    postedAt: new Date(Date.now() - 3 * 86400000),
  },
  {
    title: ".NET Full Stack Developer",
    company: "Accenture",
    companyDomain: "accenture.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "GREENHOUSE",
    applyUrl: "https://jobs.accenture.com/dotnet-fullstack",
    description: "Develop full-stack solutions for insurance clients using .NET backend and React frontend. Azure cloud deployment.",
    requirements: "4+ years .NET, 2+ years React. Azure DevOps, CI/CD pipelines. SQL Server and NoSQL databases.",
    skills: [".NET", "C#", "React", "Azure DevOps", "SQL Server", "REST API", "SOLID", "Agile"],
    salary: { min: 1600000, max: 2800000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 4 * 86400000),
  },

  // ─── DevOps / SRE ─────────────────────────────────────────────────────────
  {
    title: "Senior DevOps Engineer",
    company: "Ola",
    companyDomain: "olacabs.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "LINKEDIN",
    applyUrl: "https://www.linkedin.com/jobs/view/ola-devops-senior",
    description: "Scale Ola's ride-hailing infrastructure. Manage Kubernetes clusters, CI/CD pipelines, and observability stack.",
    requirements: "5+ years DevOps/SRE. Kubernetes at scale. Terraform, Helm, ArgoCD. On-call rotation experience.",
    skills: ["Kubernetes", "Docker", "Terraform", "Helm", "ArgoCD", "Prometheus", "Grafana", "AWS"],
    salary: { min: 2500000, max: 4000000, currency: "INR" },
    seniority: "Senior",
    postedAt: new Date(Date.now() - 1 * 86400000),
  },
  {
    title: "Site Reliability Engineer (SRE)",
    company: "Flipkart",
    companyDomain: "flipkart.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "GREENHOUSE",
    applyUrl: "https://jobs.greenhouse.io/flipkart/sre",
    description: "Maintain 99.99% uptime for Flipkart during Big Billion Days. Lead incident response and chaos engineering.",
    requirements: "4+ years SRE. Linux internals, networking fundamentals. Scripting in Python/Go/Bash. Database tuning.",
    skills: ["SRE", "Linux", "Python", "Go", "Kubernetes", "Istio", "Datadog", "Chaos Engineering"],
    salary: { min: 3000000, max: 5000000, currency: "INR" },
    seniority: "Senior",
    postedAt: new Date(Date.now() - 2 * 86400000),
  },
  {
    title: "DevOps Engineer",
    company: "Mindtree",
    companyDomain: "ltimindtree.com",
    location: "Bangalore, Karnataka",
    locationType: "ONSITE",
    jobType: "FULL_TIME",
    source: "INDEED",
    applyUrl: "https://www.indeed.com/viewjob?jk=mindtree-devops",
    description: "Build and maintain CI/CD pipelines and cloud infrastructure for Mindtree's digital transformation projects.",
    requirements: "3+ years DevOps. Jenkins, GitHub Actions. Docker, Kubernetes basics. AWS or Azure.",
    skills: ["Jenkins", "GitHub Actions", "Docker", "Kubernetes", "AWS", "Ansible", "Bash", "Linux"],
    salary: { min: 1400000, max: 2400000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 6 * 86400000),
  },

  // ─── Machine Learning / AI ────────────────────────────────────────────────
  {
    title: "Machine Learning Engineer",
    company: "Google",
    companyDomain: "google.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "LINKEDIN",
    applyUrl: "https://careers.google.com/jobs/ml-engineer-bangalore",
    description: "Build ML models that power Google Search and Ads products. Design, train, and deploy large-scale recommendation systems.",
    requirements: "4+ years ML engineering. TensorFlow or PyTorch. Strong Python, statistics, and ML fundamentals. Publications a plus.",
    skills: ["Machine Learning", "Python", "TensorFlow", "PyTorch", "MLOps", "SQL", "Spark", "GCP"],
    salary: { min: 4000000, max: 7000000, currency: "INR" },
    seniority: "Senior",
    postedAt: new Date(Date.now() - 1 * 86400000),
  },
  {
    title: "AI/ML Engineer – NLP",
    company: "PhonePe",
    companyDomain: "phonepe.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "LEVER",
    applyUrl: "https://jobs.lever.co/phonepe/nlp-ml-engineer",
    description: "Build NLP models for PhonePe's customer support automation, fraud detection, and personalisation.",
    requirements: "3+ years ML, NLP focus. Hugging Face, Transformers, BERT. Python, PyTorch. MLflow for experiment tracking.",
    skills: ["NLP", "Python", "PyTorch", "Hugging Face", "Transformers", "MLflow", "AWS", "LLMs"],
    salary: { min: 2500000, max: 4500000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 3 * 86400000),
  },
  {
    title: "Data Scientist",
    company: "Mu Sigma",
    companyDomain: "mu-sigma.com",
    location: "Bangalore, Karnataka",
    locationType: "ONSITE",
    jobType: "FULL_TIME",
    source: "INDEED",
    applyUrl: "https://www.indeed.com/viewjob?jk=mu-sigma-data-scientist",
    description: "Solve complex business problems for Fortune 500 clients using statistics, ML, and data visualisation.",
    requirements: "2+ years data science. Python or R. Scikit-learn, XGBoost, Pandas. Strong storytelling with data.",
    skills: ["Python", "R", "Scikit-learn", "XGBoost", "Pandas", "Tableau", "Statistics", "SQL"],
    salary: { min: 1200000, max: 2200000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 5 * 86400000),
  },

  // ─── Snowflake / Data Engineering ─────────────────────────────────────────
  {
    title: "Senior Snowflake Developer",
    company: "Infosys",
    companyDomain: "infosys.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "LINKEDIN",
    applyUrl: "https://www.linkedin.com/jobs/view/snowflake-developer-infosys",
    description: "Design, build, and maintain cloud data warehouse solutions on Snowflake for banking clients.",
    requirements: "5+ years data engineering, 3+ years Snowflake. dbt, Airflow, AWS.",
    skills: ["Snowflake", "SQL", "Python", "dbt", "Airflow", "AWS", "Data Engineering", "ETL"],
    salary: { min: 1800000, max: 2800000, currency: "INR" },
    seniority: "Senior",
    postedAt: new Date(Date.now() - 2 * 86400000),
  },
  {
    title: "Data Engineer (Spark + Hadoop)",
    company: "Deloitte",
    companyDomain: "deloitte.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "ADZUNA",
    applyUrl: "https://deloitte.com/careers/data-engineer-bangalore",
    description: "Build big data pipelines for Deloitte's analytics practice. Spark, Hadoop, and cloud data platforms.",
    requirements: "4+ years data engineering. Apache Spark, HDFS. Python/Scala. Cloud platform experience.",
    skills: ["Apache Spark", "Hadoop", "Python", "Scala", "Hive", "HDFS", "Kafka", "AWS"],
    salary: { min: 2000000, max: 3500000, currency: "INR" },
    seniority: "Senior",
    postedAt: new Date(Date.now() - 4 * 86400000),
  },
  {
    title: "Analytics Engineer (dbt + BigQuery)",
    company: "Freshworks",
    companyDomain: "freshworks.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "GREENHOUSE",
    applyUrl: "https://jobs.greenhouse.io/freshworks/analytics-engineer",
    description: "Own Freshworks' analytics data models using dbt and BigQuery. Bridge the gap between data engineering and data consumers.",
    requirements: "3+ years SQL, 2+ years dbt. BigQuery or Snowflake. Python for orchestration. Looker or Metabase.",
    skills: ["dbt", "BigQuery", "SQL", "Python", "Airflow", "Looker", "Analytics Engineering", "Git"],
    salary: { min: 2000000, max: 3200000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 3 * 86400000),
  },

  // ─── QA / Testing ─────────────────────────────────────────────────────────
  {
    title: "SDET – Java Automation",
    company: "ThoughtWorks",
    companyDomain: "thoughtworks.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "LEVER",
    applyUrl: "https://jobs.lever.co/thoughtworks/sdet-java",
    description: "Design test automation frameworks and champion quality engineering practices across ThoughtWorks delivery teams.",
    requirements: "3+ years test automation. Java + Selenium/Playwright. BDD with Cucumber. CI integration.",
    skills: ["Java", "Selenium", "Playwright", "Cucumber", "BDD", "TestNG", "Jenkins", "API Testing"],
    salary: { min: 1400000, max: 2500000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 2 * 86400000),
  },
  {
    title: "QA Engineer – Python Automation",
    company: "Zomato",
    companyDomain: "zomato.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "INDEED",
    applyUrl: "https://www.indeed.com/viewjob?jk=zomato-qa-python",
    description: "Build and maintain test automation suites for Zomato's web and mobile platforms using Python and Playwright.",
    requirements: "3+ years QA, 2+ years Python automation. Playwright or Selenium. API testing with Postman/pytest.",
    skills: ["Python", "Playwright", "pytest", "API Testing", "Selenium", "Postman", "CI/CD", "Jira"],
    salary: { min: 1200000, max: 2200000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 5 * 86400000),
  },

  // ─── Mobile (Android / iOS / React Native) ────────────────────────────────
  {
    title: "Android Developer (Kotlin)",
    company: "Ola",
    companyDomain: "olacabs.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "LINKEDIN",
    applyUrl: "https://www.linkedin.com/jobs/view/ola-android-kotlin",
    description: "Build next-gen features for Ola's driver and rider apps. Kotlin, Jetpack Compose, and clean architecture.",
    requirements: "3+ years Android with Kotlin. Jetpack Compose, MVVM, Hilt, Coroutines. Google Play deployment experience.",
    skills: ["Android", "Kotlin", "Jetpack Compose", "MVVM", "Hilt", "Coroutines", "REST API", "Firebase"],
    salary: { min: 2000000, max: 3500000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 2 * 86400000),
  },
  {
    title: "React Native Developer",
    company: "CRED",
    companyDomain: "cred.club",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "LEVER",
    applyUrl: "https://jobs.lever.co/cred/react-native",
    description: "Build CRED's premium mobile experience for 10M+ users. React Native, TypeScript, and pixel-perfect UI.",
    requirements: "3+ years React Native. TypeScript, Redux/Recoil. Native modules (iOS & Android). Performance optimisation.",
    skills: ["React Native", "TypeScript", "Redux", "iOS", "Android", "Firebase", "Reanimated", "Jest"],
    salary: { min: 2000000, max: 3800000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 3 * 86400000),
  },

  // ─── SAP ──────────────────────────────────────────────────────────────────
  {
    title: "SAP ABAP Developer",
    company: "Wipro",
    companyDomain: "wipro.com",
    location: "Bangalore, Karnataka",
    locationType: "ONSITE",
    jobType: "FULL_TIME",
    source: "ADZUNA",
    applyUrl: "https://www.adzuna.in/jobs/sap-abap-wipro",
    description: "Develop and maintain SAP ABAP programs, BAPIs, and enhancement spots for global manufacturing clients.",
    requirements: "4+ years SAP ABAP. Webdynpro, Smartforms, BADI, BAPI. S/4HANA experience preferred.",
    skills: ["SAP ABAP", "S/4HANA", "BAPIs", "BADI", "Webdynpro", "Smartforms", "SAP Basis", "OOABAP"],
    salary: { min: 1400000, max: 2600000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 5 * 86400000),
  },
  {
    title: "SAP Functional Consultant – FICO",
    company: "IBM",
    companyDomain: "ibm.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "GREENHOUSE",
    applyUrl: "https://jobs.greenhouse.io/ibm/sap-fico",
    description: "Configure and implement SAP FICO for IBM's global manufacturing and retail clients. Lead workshops and go-live support.",
    requirements: "5+ years SAP FICO. At least 2 full-cycle implementations. S/4HANA migration experience a strong plus.",
    skills: ["SAP FICO", "S/4HANA", "SAP General Ledger", "Asset Accounting", "Cost Center", "Controlling", "SAP FI"],
    salary: { min: 2000000, max: 3500000, currency: "INR" },
    seniority: "Senior",
    postedAt: new Date(Date.now() - 4 * 86400000),
  },

  // ─── Salesforce ───────────────────────────────────────────────────────────
  {
    title: "Salesforce Developer",
    company: "Accenture",
    companyDomain: "accenture.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "LINKEDIN",
    applyUrl: "https://jobs.accenture.com/salesforce-developer",
    description: "Build custom Salesforce solutions for Accenture's CRM practice. Apex, LWC, and Salesforce integrations.",
    requirements: "3+ years Salesforce development. Apex, LWC, Salesforce APIs. Platform Developer I certified preferred.",
    skills: ["Salesforce", "Apex", "LWC", "SOQL", "Salesforce APIs", "Flow", "Visualforce", "CPQ"],
    salary: { min: 1500000, max: 2800000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 3 * 86400000),
  },

  // ─── Business Intelligence ────────────────────────────────────────────────
  {
    title: "Power BI Developer",
    company: "KPMG India",
    companyDomain: "kpmg.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "INDEED",
    applyUrl: "https://www.indeed.com/viewjob?jk=kpmg-powerbi",
    description: "Build executive dashboards and self-service analytics for KPMG clients using Power BI and Azure Data stack.",
    requirements: "3+ years Power BI. DAX, Power Query, data modeling. SQL required. Azure Synapse a plus.",
    skills: ["Power BI", "DAX", "Power Query", "SQL", "Azure Synapse", "Data Modeling", "Excel", "Azure"],
    salary: { min: 1200000, max: 2200000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 4 * 86400000),
  },
  {
    title: "Tableau Developer / BI Analyst",
    company: "Capgemini",
    companyDomain: "capgemini.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "ADZUNA",
    applyUrl: "https://www.capgemini.com/careers/tableau-bi-analyst",
    description: "Design and develop Tableau dashboards for CPG and retail clients. Work with data teams to surface key business insights.",
    requirements: "3+ years Tableau. SQL, data blending. Tableau Server administration. Python or R for analytics.",
    skills: ["Tableau", "SQL", "Python", "Data Visualization", "Tableau Server", "Analytics", "ETL"],
    salary: { min: 1200000, max: 2200000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 6 * 86400000),
  },

  // ─── Remote / Contract roles ───────────────────────────────────────────────
  {
    title: "Go (Golang) Backend Developer",
    company: "Razorpay",
    companyDomain: "razorpay.com",
    location: "India (Remote)",
    locationType: "REMOTE",
    jobType: "FULL_TIME",
    source: "LEVER",
    applyUrl: "https://jobs.lever.co/razorpay/golang-backend",
    description: "Build high-performance payment infrastructure in Go. Handle 1M+ TPS at Razorpay's payment gateway.",
    requirements: "3+ years Go. gRPC, REST. Concurrency patterns, database internals. Distributed systems experience.",
    skills: ["Go", "Golang", "gRPC", "REST API", "MySQL", "Redis", "Kafka", "Microservices"],
    salary: { min: 2500000, max: 4500000, currency: "INR" },
    seniority: "Senior",
    postedAt: new Date(Date.now() - 2 * 86400000),
  },
  {
    title: "Cybersecurity Engineer",
    company: "Wipro",
    companyDomain: "wipro.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "LINKEDIN",
    applyUrl: "https://www.linkedin.com/jobs/view/wipro-cybersecurity",
    description: "Protect Wipro's global clients with SIEM, vulnerability management, and incident response. SIEM, SOAR, and threat hunting.",
    requirements: "4+ years cybersecurity. SIEM (Splunk/QRadar). CEH or CISSP preferred. Penetration testing knowledge.",
    skills: ["Cybersecurity", "SIEM", "Splunk", "Penetration Testing", "Incident Response", "SOAR", "Network Security", "CISSP"],
    salary: { min: 1800000, max: 3200000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 5 * 86400000),
  },
  {
    title: "Scrum Master / Agile Coach",
    company: "Cognizant",
    companyDomain: "cognizant.com",
    location: "Bangalore, Karnataka",
    locationType: "HYBRID",
    jobType: "FULL_TIME",
    source: "INDEED",
    applyUrl: "https://www.indeed.com/viewjob?jk=cognizant-scrum-master",
    description: "Coach 3 agile delivery teams at Cognizant. Remove impediments, facilitate ceremonies, drive DevOps practices.",
    requirements: "4+ years as Scrum Master. CSM or PSM certified. Jira, Confluence. Experience with SAFe is a plus.",
    skills: ["Scrum", "Agile", "SAFe", "Jira", "Confluence", "Kanban", "Coaching", "CSM"],
    salary: { min: 1800000, max: 3000000, currency: "INR" },
    seniority: "Mid",
    postedAt: new Date(Date.now() - 7 * 86400000),
  },
];

async function main() {
  console.log("🌱 Seeding database with diverse IT jobs...\n");

  // Clear existing jobs first for a clean seed
  await db.savedJob.deleteMany({});
  await db.job.deleteMany({});
  console.log("🗑️  Cleared existing jobs\n");

  let created = 0;

  for (const job of JOBS) {
    const { companyDomain, ...jobData } = job;
    await db.job.create({
      data: {
        ...jobData,
        locationType: jobData.locationType as "HYBRID" | "REMOTE" | "ONSITE",
        jobType: jobData.jobType as "FULL_TIME" | "PART_TIME" | "CONTRACT" | "INTERNSHIP" | "FREELANCE",
        source: jobData.source as "LINKEDIN" | "INDEED" | "GREENHOUSE" | "LEVER" | "ADZUNA" | "MANUAL",
        companyLogo: `https://logo.clearbit.com/${companyDomain}`,
        isActive: true,
      },
    });
    created++;
    console.log(`  ✓ [${jobData.skills[0]?.padEnd(20)}] ${jobData.title} @ ${jobData.company}`);
  }

  console.log(`\n✅ Done! Created ${created} jobs across Java, Python, Azure, .NET, React, DevOps, ML, QA, Mobile, SAP, Salesforce, BI.`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
